version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - data:/var/lib/mysql
    restart: always
  web:
    environment:
      DB_HOST: db
      DB_NAME: database
      DB_USER: user
      DB_PASSWORD: secret
    build: .
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/usr/local/lib/php-micro
      - ./example/:/var/www/html
    ports:
      - "3000:80"
    working_dir: /var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '3001:80'
    volumes:
      - /sessions
  composer:
    image: composer
    command: install
    working_dir: /var/www/html
    depends_on:
      - web
    volumes:
      - .:/usr/local/lib/php-micro
      - ./example/composer.json:/var/www/html/composer.json
      - ./example/composer.lock:/var/www/html/composer.lock
      - ./example/vendor:/var/www/html/vendor
volumes:
  data:
